HMSystem/Areas/Dashboard/ViewModels/AccomodationPackageViewModel.cs
using HMSystem.Entities;
using HMSystem.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HMSystem.Areas.Dashboard.ViewModels
{
    public class AccomodationPackagesListingModel
    {
        public IEnumerable<AccomodationPackage> AccomodationPackages { get; set; }
        public int? AccomodationTypeID { get; set; }
        public IEnumerable<AccomodationType> AccomodationTypes { get; set; }
        public string SearchTerm { get; set; }

        public Pager Pager { get; set; }
    }

    public class AccomodationPackageActionModel
    {
        public int ID { get; set; }

        public int AccomodationTypeID { get; set; }
        public AccomodationType AccomodationType { get; set; }

        public string Name { get; set; }
        public int NoOfRoom { get; set; }
        public decimal FeePerNight { get; set; }

        public string PictureIDs { get; set; }

        public IEnumerable<AccomodationType> AccomodationTypes { get; set; }
        public List<AccomodationPackagePicture> AccomodationPackagePictures { get; set; }
    }
}

HMSystem/Areas/Dashboard/Controllers/AccomodationPackagesController.cs
using HMS.Services;
using HMSystem.Areas.Dashboard.ViewModels;
using HMSystem.Entities;
using HMSystem.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace HMSystem.Areas.Dashboard.Controllers
{
    public class AccomodationPackagesController : Controller
    {
        AccomodationPackagesService accomodationPackagesService = new AccomodationPackagesService();
        AccomodationTypesService accomodationTypesService = new AccomodationTypesService();
        DashboardsService dashboardsService = new DashboardsService();

        public ActionResult Index(string searchTerm, int? accomodationTypeID, int? page)
        {
            int recordSize = 5;
            page = page ?? 1;

            AccomodationPackagesListingModel model = new AccomodationPackagesListingModel();

            model.SearchTerm = searchTerm;
            model.AccomodationTypeID = accomodationTypeID;

            model.AccomodationPackages = accomodationPackagesService.SearchAccomodationPackages(searchTerm, accomodationTypeID, page.Value, recordSize);

            model.AccomodationTypes = accomodationTypesService.GetAllAccomodationTypes();

            var totalRecords = accomodationPackagesService.SearchAccomodationPackagesCount(searchTerm, accomodationTypeID);

            model.Pager = new Pager(totalRecords, page, recordSize);

            return View(model);
        }

        [HttpGet]
        public ActionResult Action(int? ID)
        {
            AccomodationPackageActionModel model = new AccomodationPackageActionModel();

            if (ID.HasValue) //we are trying to edit a record
            {
                var accomodationPackage = accomodationPackagesService.GetAccomodationPackageByID(ID.Value);

                model.ID = accomodationPackage.ID;
                model.AccomodationTypeID = accomodationPackage.AccomodationTypeID;
                model.Name = accomodationPackage.Name;
                model.NoOfRoom = accomodationPackage.NoOfRoom;
                model.FeePerNight = accomodationPackage.FeePerNight;

                model.AccomodationPackagePictures = accomodationPackagesService.GetPicturesByAccomodationPackageID(accomodationPackage.ID);
            }

            model.AccomodationTypes = accomodationTypesService.GetAllAccomodationTypes();

            return PartialView("_Action", model);
        }

        [HttpPost]
        public JsonResult Action(AccomodationPackageActionModel model)
        {
            JsonResult json = new JsonResult();

            var result = false;

            //model.PictureIDs = "90,67,23" = ["90", "67", "23"] = {90, 67, 23}
            List<int> pictureIDs = !string.IsNullOrEmpty(model.PictureIDs) ? model.PictureIDs.Split(',').Select(x => int.Parse(x)).ToList() : new List<int>();
            var pictures = dashboardsService.GetPicturesByIDs(pictureIDs);


            if (model.ID > 0) //we are trying to edit a record
            {
                var accomodationPackage = accomodationPackagesService.GetAccomodationPackageByID(model.ID);

                accomodationPackage.AccomodationTypeID = model.AccomodationTypeID;
                accomodationPackage.Name = model.Name;
                accomodationPackage.NoOfRoom = model.NoOfRoom;
                accomodationPackage.FeePerNight = model.FeePerNight;

                accomodationPackage.AccomodationPackagePictures.Clear();
                accomodationPackage.AccomodationPackagePictures.AddRange(pictures.Select(x => new AccomodationPackagePicture() { AccomodationPackageID = accomodationPackage.ID, PictureID = x.ID }));

                result = accomodationPackagesService.UpdateAccomodationPackage(accomodationPackage);
            }
            else //we are trying to create a record
            {
                AccomodationPackage accomodationPackage = new AccomodationPackage();

                accomodationPackage.AccomodationTypeID = model.AccomodationTypeID;
                accomodationPackage.Name = model.Name;
                accomodationPackage.Name = model.Name;
                accomodationPackage.NoOfRoom = model.NoOfRoom;
                accomodationPackage.FeePerNight = model.FeePerNight;


              

                accomodationPackage.AccomodationPackagePictures = new List<AccomodationPackagePicture>();
                accomodationPackage.AccomodationPackagePictures.AddRange(pictures.Select(x => new AccomodationPackagePicture() { PictureID = x.ID }));


                result = accomodationPackagesService.SaveAccomodationPackage(accomodationPackage);
            }

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Accomodation Package." };
            }

            return json;
        }

        [HttpGet]
        public ActionResult Delete(int ID)
        {
            AccomodationPackageActionModel model = new AccomodationPackageActionModel();

            var accomodationPackage = accomodationPackagesService.GetAccomodationPackageByID(ID);

            model.ID = accomodationPackage.ID;

            return PartialView("_Delete", model);
        }

        [HttpPost]
        public JsonResult Delete(AccomodationPackageActionModel model)
        {
            JsonResult json = new JsonResult();

            var result = false;

            var accomodationPackage = accomodationPackagesService.GetAccomodationPackageByID(model.ID);

            result = accomodationPackagesService.DeleteAccomodationPackage(accomodationPackage);

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Accomodation Package." };
            }

            return json;
        }
    }
}

HMSystem/Areas/Dashboard/Controllers/DashboardController.cs
using HMS.Services;
using HMSystem.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMSystem.Areas.Dashboard.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard/Dashboard
        //[Authorize(Roles ="Administrator")]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult UploadPictures()
        {
            JsonResult result = new JsonResult();

            var dashboardService = new DashboardsService();
            var picList = new List<Picture>();

            var files = Request.Files;

            for (int i = 0; i < files.Count; i++)
            {
                var picture = files[i];

                var fileName = Guid.NewGuid() + picture.FileName + Path.GetExtension(picture.FileName);
                var filePath = Server.MapPath("~/images/site/") + fileName;

                picture.SaveAs(filePath);

                var dbPicture = new Picture();
                dbPicture.URL = fileName;

                if(dashboardService.SavePicture(dbPicture))
                {
                    picList.Add(dbPicture);
                }
            }
            result.Data = picList;

            return result;
        }
    }
}

HMSystem/Areas/Dashboard/Views/AccomodationPackages/Index.cshtml
@model HMSystem.Areas.Dashboard.ViewModels.AccomodationPackagesListingModel


<div class="row">
    <div class="col col-lg-12">
        <h2>Accomodation Types</h2>
        <hr />
    </div>
</div>

<div class="row mb-3">
    <div class="col col-lg-12">
        <form>
            <div class="input-group">
                <input type="text" name="searchTerm" class="form-control" placeholder="Search." value="@Model.SearchTerm">

                @if (Model.AccomodationTypes != null && Model.AccomodationTypes.Count() > 0)
                {
                    <select name="AccomodationTypeID" class="form-control">
                        <option value="0">
                            Select type
                        </option>
                        @foreach (var accomdationTypes in Model.AccomodationTypes)
                        {
                            <option value="@accomdationTypes.ID" @(accomdationTypes.ID == Model.AccomodationTypeID ? "selected" : string.Empty) >
                                @accomdationTypes.Name
                            </option>
                        }
                    </select>
                }

                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="submit"><i class="fas fa-search mr-1"></i>Search</button>
                    <a class="btn btn-outline-secondary" href="@Url.Action("Index", "AccomodationPackages")"><i class="fas fa-redo mr-1"></i>Reset</a>
                    <button data-href="@Url.Action("Action", "AccomodationPackages")" class="data-btn btn btn-outline-success" type="button" data-toggle="modal" data-target="#actionModal"><i class="fas fa-plus-circle mr-1"></i>Create</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col col-lg-12">
        @{
            Html.RenderPartial("_Listing");
        }
    </div>
</div>

<div class="modal fade" id="actionModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
    </div>
</div>

<script>
    $(".data-btn").click(function () {
        $.ajax({
            url: $(this).attr("data-href"),
        })
            .done(function (response) {
                $("#actionModal .modal-dialog").html(response);
            });
    });
</script> 

HMSystem/Areas/Dashboard/Views/AccomodationPackages/_Action.cshtml
@model HMSystem.Areas.Dashboard.ViewModels.AccomodationPackageActionModel

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                @if (Model.ID > 0)
                {
                    <span>Edit Accomodation Package</span>
                }
                else
                {
                    <span>Create Accomodation Package</span>
                }
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <input type="hidden" name="ID" value="@Model.ID" />

                <div class="form-group">
                    <label>Accomodation Type</label>
                    <select class="form-control" name="AccomodationTypeID">
                        @if (Model.AccomodationTypes != null)
                        {
                            foreach (var accomodationType in Model.AccomodationTypes)
                            {
                                <option value="@accomodationType.ID" @(accomodationType.ID == Model.AccomodationTypeID ? "selected" : string.Empty)>
                                    @accomodationType.Name
                                </option>
                            }
                        }
                    </select>
                </div>

                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" name="Name" placeholder="Enter Accomodation Package Name." value="@Model.Name">
                </div>
                <div class="form-group">
                    <label>No Of Rooms</label>
                    <input class="form-control" name="NoOfRoom" placeholder="Enter No Of Rooms." value="@Model.NoOfRoom">
                </div>
                <div class="form-group">
                    <label>FeePerNight</label>
                    <input class="form-control" name="FeePerNight" placeholder="Enter Fee Per Night." value="@Model.FeePerNight">
                </div>

                <div class="form-group">
                    <label>Pictures</label>
                    <input class="form-control" id="selectPictures" name="Pictures" type="file" multiple >
                    <input type="hidden" name="pictureIDs" id="pictureIDs" value="" />
                </div>

                <div id="picturesArea">
                    @if (Model.AccomodationPackagePictures != null && Model.AccomodationPackagePictures.Count > 0)
                    {
                        foreach (var accomodationPicture in Model.AccomodationPackagePictures)
                        {
                            <img src="/images/site/@accomodationPicture.Picture.URL" class="img-fluid" style="width:200px" onclick="removeMe(this)" data-id="@accomodationPicture.PictureID" />
                        }
                    }
                </div>
            </form>

            <div class="errorDiv">

            </div>
        </div>
        <div class="modal-footer">
            <button id="actionButton" type="button" class="btn btn-primary"><i class="fas fa-save mr-1"></i> Save</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times mr-1"></i> Close</button>
        </div>
    </div>
}
<div id="imageTemplate">
    <img src="" class="img-fluid" style="width:200px" onclick="removeMe(this)"  />
</div>

<script>
    $("#actionButton").click(function () {

        var pictureIDs = [];
        $("#picturesArea img").each(function () {
            var picID = $(this).attr("data-id");

            pictureIDs.push(picID);
        });

        $("#pictureIDs").val(pictureIDs.join());

		$.ajax({
			url: '@Url.Action("Action", "AccomodationPackages")',
			type: "post",
			data: $("#actionForm").serialize()
		})
		.done(function (response) {
			if(response.Success)
			{
				location.reload();
			}
			else {
				$(".errorDiv").html(response.Message);
			}
		});
    });

    $("#selectPictures").change(function () {

        var pictures = this.files;

        var formData = new FormData();

        for (var i = 0; i < pictures.length; i++) {
            formData.append("Picture", pictures[i]);
        }

		$.ajax({
			url: '@Url.Action("UploadPictures", "Dashboard")',
            type: "post",
            data: formData,
            processData: false,
			contentType: false
		})
        .done(function (response) {

            for (var i = 0; i < response.length; i++) {
                var picture = response[i];

                var $imgHTML = $("#imageTemplate").clone();

                $imgHTML.find("img").attr("src", "/images/site/" + picture.URL);
                $imgHTML.find("img").attr("data-id", picture.ID);

                $("#picturesArea").append($imgHTML.html());
            }
		});
    });

    function removeMe(element) {
        element.remove();
    }

</script>

HMSystem/Areas/Dashboard/Views/AccomodationPackages/_Delete.cshtml
@model HMSystem.Areas.Dashboard.ViewModels.AccomodationPackageActionModel

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                <span>Delete Accomodation Package</span>
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <input type="hidden" name="ID" value="@Model.ID" />
            </form>
            <div class="alert alert-danger" role="alert">
                Are you sure you want to delete this Accomodation Package?
            </div>
        </div>
        <div class="modal-footer">
            <button id="actionButton" type="button" class="btn btn-danger"><i class="fas fa-trash-alt mr-1"></i> Delete</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times mr-1"></i> Close</button>
        </div>
    </div>
}

<script>
	$("#actionButton").click(function () {
		$.ajax({
			url: '@Url.Action("Delete", "AccomodationPackages")',
			type: "post",
			data: $("#actionForm").serialize()
		})
		.done(function (response) {
			if(response.Success)
			{
				window.location.href = "@Url.Action("Index", "AccomodationPackages")";
			}
			else {
				$(".errorDiv").html(response.Message);
			}
		});
	});
</script>

HMSystem/Areas/Dashboard/Views/AccomodationPackages/_Listing.cshtml
@model HMSystem.Areas.Dashboard.ViewModels.AccomodationPackagesListingModel

@if (Model != null && Model.AccomodationPackages != null && Model.AccomodationPackages.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Fee Per Night</th>
                <th scope="col">Accomodation Type</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var accomodationPackage in Model.AccomodationPackages)
            {
                <tr>
                    <td>
                        @accomodationPackage.Name
                    </td>
                    <td>
                        @accomodationPackage.FeePerNight
                    </td>
                    <td>
                        @if (accomodationPackage.AccomodationType != null)
                        {
                            @accomodationPackage.AccomodationType.Name
                        }
                    </td>
                    <td>
                        <button data-href="@Url.Action("Action", "AccomodationPackages", new { ID = accomodationPackage.ID })" type="button" class="data-btn btn btn-primary" data-toggle="modal" data-target="#actionModal"><i class="fas fa-pen mr-1"></i> Edit</button>
                        <button data-href="@Url.Action("Delete", "AccomodationPackages", new { ID = accomodationPackage.ID })" type="button" class="data-btn btn btn-danger" data-toggle="modal" data-target="#actionModal"><i class="fas fa-trash-alt mr-1"></i> Delete</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    if (Model.Pager.EndPage > 1)
    {
        <nav>
            <ul class="pagination">
                @if (Model.Pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "AccomodationPackages")">
                            <i class="fas fa-angle-double-left"></i>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "AccomodationPackages", new { page = Model.Pager.CurrentPage - 1, searchTerm = Model.SearchTerm, accomodationTypeID = Model.AccomodationTypeID })">
                            <i class="fas fa-angle-left"></i>
                        </a>
                    </li>
                }

                @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                    <li class="page-item @(page == Model.Pager.CurrentPage ? "active" : "")">
                        <a class="page-link" href="@Url.Action("Index", "AccomodationPackages", new { page = page, searchTerm = Model.SearchTerm, accomodationTypeID = Model.AccomodationTypeID })">@page</a>
                    </li>
                }

                @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "AccomodationPackages", new { page = Model.Pager.CurrentPage + 1, searchTerm = Model.SearchTerm, accomodationTypeID = Model.AccomodationTypeID })">
                            <i class="fas fa-angle-right"></i>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "AccomodationPackages", new { page = Model.Pager.TotalPages, searchTerm = Model.SearchTerm, accomodationTypeID = Model.AccomodationTypeID })">
                            <i class="fas fa-angle-double-right"></i>
                        </a>
                    </li>
                }
            </ul>
        </nav>
    }
}
else
{
    <div class="alert alert-warning" role="alert">
        Sorry, No record found!
    </div>
}