HMSystem/Areas/Dashboard/ViewModels/AccomodationTypesViewModel.cs
using HMSystem.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HMSystem.Areas.Dashboard.ViewModels
{
    public class AccomodationTypesListingModel
    {
        public IEnumerable<AccomodationType> AccomodationTypes { get; set; }
        public string SearchTerm { get; set; }
    }

    public class AccomodationTypesAddOrEditModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

HMSystem/Areas/Dashboard/Controllers/AccomodationTypesController.cs
using HMS.Services;
using HMSystem.Areas.Dashboard.ViewModels;
using HMSystem.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMSystem.Areas.Dashboard.Controllers
{
    public class AccomodationTypesController : Controller
    {
        AccomodationTypesService accomodationTypesService = new AccomodationTypesService();

        public ActionResult Index(string searchTerm)
        {

            AccomodationTypesListingModel model = new AccomodationTypesListingModel();

            model.SearchTerm = searchTerm;


            model.AccomodationTypes = accomodationTypesService.SearchAccomodationTypes(searchTerm);

            return View(model);
        }


        [HttpGet]
        public ActionResult Action(int? ID)
        {
            AccomodationTypesAddOrEditModel model = new AccomodationTypesAddOrEditModel();

            if(ID.HasValue)
            {
                var accomodationType = accomodationTypesService.GetAccomodationTypeByID(ID.Value);

                model.ID = accomodationType.ID;
                model.Name = accomodationType.Name;
                model.Description = accomodationType.Description;
            }

            return PartialView("_AddOrEdit", model);
        }

        [HttpPost]
        public JsonResult Action(AccomodationTypesAddOrEditModel model)
        {
            JsonResult json = new JsonResult();

            var result = false;

            if(model.ID > 0)
            {
                var accomodationType = accomodationTypesService.GetAccomodationTypeByID(model.ID);

                accomodationType.Name = model.Name;
                accomodationType.Description = model.Name;

                result = accomodationTypesService.UpdateAccomodationType(accomodationType);
            }
            else
            {
                AccomodationType accomodationType = new AccomodationType();

                accomodationType.Name = model.Name;
                accomodationType.Description = model.Description;

                result = accomodationTypesService.SaveAccomodationType(accomodationType);
            }

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Accomodation Type." };
            }

            return json;
        }

        public ActionResult Delete(int ID)
        {
            AccomodationTypesAddOrEditModel model = new AccomodationTypesAddOrEditModel();

            var accomodationType = accomodationTypesService.GetAccomodationTypeByID(ID);

            model.ID = accomodationType.ID;

            return PartialView("_Delete", model);
        }

        [HttpPost]
        public JsonResult Delete(AccomodationTypesAddOrEditModel model)
        {
            JsonResult json = new JsonResult();

            var result = false;

            var accomodationType = accomodationTypesService.GetAccomodationTypeByID(model.ID);

            result = accomodationTypesService.DeleteAccomodationType(accomodationType);

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Accomodation Type." };
            }

            return json;
        }
    }
}

HMSystem/Areas/Dashboard/Views/AccomodationTypes/Index.cshtml
@model HMSystem.Areas.Dashboard.ViewModels.AccomodationTypesListingModel

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col col-lg-12">
        <h2>Accomodation Types</h2>
        <hr />
    </div>
</div>

<div class="row mb-3">
    <div class="col col-lg-12">
        <form>
            <div class="input-group">
                <input type="text" name="searchTerm" class="form-control" placeholder="Search."  value="@Model.SearchTerm" required>
                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="submit"><i class="fas fa-search mr-1"></i>Search</button>
                    <a class="btn btn-outline-secondary" href="@Url.Action("Index", "AccomodationTypes")"><i class="fas fa-redo mr-1"></i>Reset</a>
                    <button data-href="@Url.Action("Action", "AccomodationTypes")" class="data-btn btn btn-outline-success" type="button" data-toggle="modal" data-target="#actionModal"><i class="fas fa-plus-circle mr-1"></i>Create</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col col-lg-12">
        @{
            Html.RenderPartial("_Listing", Model);
        }
    </div>
</div>

<div class="modal fade" id="actionModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
    </div>
</div>

<script>
    $(".data-btn").click(function () {
        $.ajax({
            url: $(this).attr("data-href"),
		})
		.done(function (response) {
			$("#actionModal .modal-dialog").html(response);
		});
	});
</script> 

HMSystem/Areas/Dashboard/Views/AccomodationTypes/_AddOrEdit.cshtml
@model HMSystem.Areas.Dashboard.ViewModels.AccomodationTypesAddOrEditModel

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                @if(Model.ID > 0)
                {
                    <span>Edit Accomodation Type</span>
                }
                else
                {
                    <span>Create Accomodation Type</span>
                }

                </h5>
    
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <input type="hidden" name="ID" value="@Model.ID" />
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" name="Name" placeholder="Enter Accomodation Type Name." value="@Model.Name">
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <textarea class="form-control" name="Description" placeholder="Enter Accomodation Type Description.">@Model.Description</textarea>
                </div>
            </form>

            <div class="errorDiv">

            </div>
        </div>
        <div class="modal-footer">
            <button id="actionButton" type="button" class="btn btn-primary"><i class="far fa-save mr-1"></i>Save</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="far fa-window-close mr-1"></i>Close</button>
        </div>
    </div>
}

<script>
	$("#actionButton").click(function () {
		$.ajax({
			url: '@Url.Action("Action", "AccomodationTypes")',
			type: "post",
			data: $("#actionForm").serialize()
		})
		.done(function (response) {
			debugger;
			if(response.Success)
			{
				location.reload();
			}
			else {
				$(".errorDiv").html(response.Message);
			}
		});
	});
</script>

HMSystem/Areas/Dashboard/Views/AccomodationTypes/_Delete.cshtml
@model HMSystem.Areas.Dashboard.ViewModels.AccomodationTypesAddOrEditModel

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                Delete Accomodation Type
            </h5>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <input type="hidden" name="ID" value="@Model.ID" />

                <div class="alert alert-danger" role="alert">
                    Are you sure you want to delete this accomadation type!
                </div>
            </form>

        </div>
        <div class="modal-footer">
            <button id="actionButton" type="button" class="btn btn-primary"><i class="far fa-trash-alt mr-1"></i>Delete</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="far fa-window-close mr-1"></i>Close</button>
        </div>
    </div>
}

<script>
	$("#actionButton").click(function () {
		$.ajax({
			url: '@Url.Action("Delete", "AccomodationTypes")',
			type: "post",
			data: $("#actionForm").serialize()
		})
		.done(function (response) {
			debugger;
			if(response.Success)
			{
				window.location.href = "@Url.Action("Index", "AccomodationTypes")";
			}
			else {
				$(".errorDiv").html(response.Message);
			}
		});
	});
</script>

HMSystem/Areas/Dashboard/Views/AccomodationTypes/_Listing.cshtml
@model HMSystem.Areas.Dashboard.ViewModels.AccomodationTypesListingModel

@if (Model != null && Model.AccomodationTypes != null && Model.AccomodationTypes.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var accomdationType in Model.AccomodationTypes)
            {
                <tr>
                    <td>
                        @accomdationType.Name
                    </td>

                    <td>
                        @accomdationType.Description
                    </td>

                    <td>
                        <button data-href="@Url.Action("Action", "AccomodationTypes", new { ID = accomdationType.ID})" type="button" class="data-btn btn btn-primary" data-toggle="modal" data-target="#actionModal"><i class="far fa-edit mr-1"></i>Edit</button>
                        <button data-href="@Url.Action("Delete", "AccomodationTypes", new { ID = accomdationType.ID})" type="button" class="data-btn btn btn-danger" data-toggle="modal" data-target="#actionModal"><i class="far fa-trash-alt mr-1"></i>Delete</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning" role="alert">
       Sorry, No record found!
    </div>
}